version: '3.4'
services:
  db:
    image: postgres:10
    volumes:
      - crunchbase-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    image: the645test
    command: bash -c "bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DISABLE_FILE_WATCHER: true
#      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - db
volumes:
  crunchbase-data:
    name: crunchbase-postgres-data
    driver: local
